# Generated by Django 5.2.4 on 2025-08-11 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0002_rename_user_reservation_seller'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='seller',
            new_name='consumer',
        ),
    ]
