# Generated by Django 5.2.4 on 2025-08-16 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0003_rename_seller_reservation_consumer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirm', 'Confirm'), ('pickup', 'PickUp'), ('cancel', 'Cancel')], default='pending', max_length=20),
        ),
    ]
