# Generated by Django 5.2.4 on 2025-08-11 18:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('products', '0002_rename_user_wishlist_consumer_alter_product_seller_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userrecommendedkeyword',
            name='user',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_seller',
        ),
        migrations.RemoveField(
            model_name='user',
            name='nickname',
        ),
        migrations.AddField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(default='default', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('consumer', '소비자'), ('seller', '판매자')], default='consumer', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=128, verbose_name='password'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.CreateModel(
            name='RecommendedKeyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=100)),
                ('score', models.FloatField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('consumer', models.ForeignKey(limit_choices_to={'role': 'consumer'}, on_delete=django.db.models.deletion.CASCADE, related_name='recommended_keywords', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('consumer', 'keyword')},
            },
        ),
        migrations.DeleteModel(
            name='Seller',
        ),
        migrations.DeleteModel(
            name='UserRecommendedKeyword',
        ),
    ]
