# Generated by Django 5.2.4 on 2025-08-12 11:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_auto_add_initial_data'),
        ('products', '0004_alter_product_store'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(default='products/22.PNG', upload_to='products/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='categories.category'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='discount_price',
            field=models.PositiveIntegerField(default=1000),
            preserve_default=False,
        ),
    ]
